name = "cloudflare-hello-world"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "/static/",entry-point = "workers-site"}
compatibility_date = "2021-11-18"
